<?php

use Illuminate\Database\Seeder;

class WorkExpTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('work_exp')->delete();
        
        \DB::table('work_exp')->insert(array (
            0 => 
            array (
                'id' => 1,
                'master_code' => 'AA7242',
                'document_id' => 17,
                'doc_number' => 'RR/UNJBG547-548',
                'date_expedition' => '2017-07-05',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-14',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:16:55',
                'updated_at' => '2017-07-22 02:16:55',
            ),
            1 => 
            array (
                'id' => 2,
                'master_code' => 'AA7242',
                'document_id' => 17,
                'doc_number' => 'RR/UNJBG548-548',
                'date_expedition' => '2017-07-11',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-11',
                'until' => '2017-07-18',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:18:07',
                'updated_at' => '2017-07-22 02:18:07',
            ),
            2 => 
            array (
                'id' => 3,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'AC/UNJBG-548545',
                'date_expedition' => '2017-07-11',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-12',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:19:21',
                'updated_at' => '2017-07-22 02:19:21',
            ),
            3 => 
            array (
                'id' => 4,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'CD/UNJBG-658745',
                'date_expedition' => '2017-07-19',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 2,
                'condition' => 'Condicion',
                'since' => '2017-07-17',
                'until' => '2017-07-25',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:20:06',
                'updated_at' => '2017-07-22 02:20:06',
            ),
            4 => 
            array (
                'id' => 5,
                'master_code' => 'AA7242',
                'document_id' => 6,
                'doc_number' => 'CT/UNJBG-511454',
                'date_expedition' => '2017-07-19',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-06-28',
                'until' => '2017-07-26',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:21:00',
                'updated_at' => '2017-07-22 02:21:00',
            ),
            5 => 
            array (
                'id' => 6,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'FF/UNJBG-985658',
                'date_expedition' => '2017-07-11',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-12',
                'until' => '2017-08-10',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:32:54',
                'updated_at' => '2017-07-22 02:32:54',
            ),
            6 => 
            array (
                'id' => 7,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'GG/UNJBG-658745',
                'date_expedition' => '2017-07-12',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 4,
                'condition' => 'Condicion',
                'since' => '2017-07-05',
                'until' => '2017-07-11',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:33:49',
                'updated_at' => '2017-07-22 02:33:49',
            ),
            7 => 
            array (
                'id' => 8,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'DD/UNJBG-564121',
                'date_expedition' => '2017-07-12',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-12',
                'until' => '2017-07-20',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:36:02',
                'updated_at' => '2017-07-22 02:36:02',
            ),
            8 => 
            array (
                'id' => 9,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'EE/UNJBG-625147',
                'date_expedition' => '2017-07-19',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-05',
                'until' => '2017-07-19',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:36:49',
                'updated_at' => '2017-07-22 02:36:49',
            ),
            9 => 
            array (
                'id' => 10,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'EE/UNJBG-547874',
                'date_expedition' => '2017-07-12',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 5,
                'condition' => 'Condicion',
                'since' => '2017-06-28',
                'until' => '2017-07-18',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:37:46',
                'updated_at' => '2017-07-22 02:37:46',
            ),
            10 => 
            array (
                'id' => 11,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'SS/UNJBG-478458',
                'date_expedition' => '2017-07-12',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 4,
                'condition' => 'Condicion',
                'since' => '2017-07-12',
                'until' => '2017-07-27',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:39:16',
                'updated_at' => '2017-07-22 02:39:16',
            ),
            11 => 
            array (
                'id' => 12,
                'master_code' => 'AA7242',
                'document_id' => 1,
                'doc_number' => 'JJ/UNJBG-478547',
                'date_expedition' => '2017-07-12',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-06-27',
                'until' => '2017-07-18',
                'institution' => 'Institucion',
                'observation' => 'Observacion',
                'created_at' => '2017-07-22 02:40:03',
                'updated_at' => '2017-07-22 02:40:03',
            ),
            12 => 
            array (
                'id' => 13,
                'master_code' => 'AA7242',
                'document_id' => 13,
                'doc_number' => 'OC/UNJBG-658975',
                'date_expedition' => '2017-07-20',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-11',
                'until' => '2017-07-18',
                'institution' => 'Institucion',
                'observation' => 'Observaciones',
                'created_at' => '2017-07-23 04:39:24',
                'updated_at' => '2017-07-23 04:39:24',
            ),
            13 => 
            array (
                'id' => 14,
                'master_code' => 'AA7242',
                'document_id' => 6,
                'doc_number' => 'CT/UNJBG-121545',
                'date_expedition' => '2017-07-20',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 1,
                'condition' => 'Condicion',
                'since' => '2017-07-11',
                'until' => '2017-07-18',
                'institution' => 'Institucion',
                'observation' => 'Observaciones',
                'created_at' => '2017-07-23 19:12:37',
                'updated_at' => '2017-07-23 19:12:37',
            ),
            14 => 
            array (
                'id' => 15,
                'master_code' => 'AA7242',
                'document_id' => 7,
                'doc_number' => 'CS/UNJBG-548745',
                'date_expedition' => '2017-08-16',
                'position_id' => 4,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-07',
                'until' => '2017-08-17',
                'institution' => 'Institucion',
                'observation' => 'Observaciones',
                'created_at' => '2017-07-26 22:57:34',
                'updated_at' => '2017-07-26 22:57:34',
            ),
            15 => 
            array (
                'id' => 16,
                'master_code' => 'AA7242',
                'document_id' => 6,
                'doc_number' => 'CT/UNJBG-597554',
                'date_expedition' => '2017-07-12',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-12',
                'until' => '2017-07-26',
                'institution' => 'Institucion',
                'observation' => 'Observaciones',
                'created_at' => '2017-07-26 23:00:32',
                'updated_at' => '2017-07-26 23:00:32',
            ),
            16 => 
            array (
                'id' => 17,
                'master_code' => 'AA7242',
                'document_id' => 7,
                'doc_number' => 'CN/UNJBG-125478',
                'date_expedition' => '2017-07-24',
                'position_id' => 4,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-08-08',
                'until' => '2017-08-16',
                'institution' => 'Institucion',
                'observation' => 'Observaciones',
                'created_at' => '2017-07-26 23:41:18',
                'updated_at' => '2017-07-26 23:41:18',
            ),
            17 => 
            array (
                'id' => 18,
                'master_code' => 'AA7242',
                'document_id' => 4,
                'doc_number' => 'RR/UNJBG-224455',
                'date_expedition' => '2017-06-29',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 2,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-04',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-26 23:54:40',
                'updated_at' => '2017-07-26 23:54:40',
            ),
            18 => 
            array (
                'id' => 19,
                'master_code' => 'AA7242',
                'document_id' => 7,
                'doc_number' => 'CN/UNJBG-548756',
                'date_expedition' => '2017-07-05',
                'position_id' => 4,
                'recognized' => 1,
                'labor_id' => 2,
                'condition' => 'Condicion',
                'since' => '2017-07-28',
                'until' => '2017-08-09',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:19:53',
                'updated_at' => '2017-07-27 00:19:53',
            ),
            19 => 
            array (
                'id' => 20,
                'master_code' => 'AA7242',
                'document_id' => 5,
                'doc_number' => 'CT/UNJBG-597559',
                'date_expedition' => '2017-08-10',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 4,
                'condition' => 'Condicion',
                'since' => '2017-08-09',
                'until' => '2017-08-18',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:21:51',
                'updated_at' => '2017-07-27 00:21:51',
            ),
            20 => 
            array (
                'id' => 21,
                'master_code' => 'AA7242',
                'document_id' => 4,
                'doc_number' => 'RR/UNJBG-224499',
                'date_expedition' => '2017-08-16',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-08-09',
                'until' => '2017-08-17',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:22:44',
                'updated_at' => '2017-07-27 00:22:44',
            ),
            21 => 
            array (
                'id' => 22,
                'master_code' => 'AA7242',
                'document_id' => 8,
                'doc_number' => 'RR/UNJBG-224477',
                'date_expedition' => '2017-07-13',
                'position_id' => 5,
                'recognized' => 1,
                'labor_id' => 5,
                'condition' => 'Condicion',
                'since' => '2017-07-10',
                'until' => '2017-07-27',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:23:31',
                'updated_at' => '2017-07-27 00:23:31',
            ),
            22 => 
            array (
                'id' => 23,
                'master_code' => 'AA7242',
                'document_id' => 6,
                'doc_number' => 'RR/UNJBG-224433',
                'date_expedition' => '2017-06-30',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-04',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:31:57',
                'updated_at' => '2017-07-27 00:31:57',
            ),
            23 => 
            array (
                'id' => 24,
                'master_code' => 'AA7242',
                'document_id' => 4,
                'doc_number' => 'RR/UNJBG-224453',
                'date_expedition' => '2017-07-14',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-19',
                'until' => '2017-07-19',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 00:38:14',
                'updated_at' => '2017-07-27 00:38:14',
            ),
            24 => 
            array (
                'id' => 25,
                'master_code' => 'AA7242',
                'document_id' => 4,
                'doc_number' => 'RR/UNJBG-224446',
                'date_expedition' => '2017-07-13',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 4,
                'condition' => 'Condicion',
                'since' => '2017-07-19',
                'until' => '2017-07-10',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 01:04:01',
                'updated_at' => '2017-07-27 01:04:01',
            ),
            25 => 
            array (
                'id' => 26,
                'master_code' => 'AA7242',
                'document_id' => 3,
                'doc_number' => 'RR/UNJBG-224479',
                'date_expedition' => '2017-08-09',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-08-09',
                'until' => '2017-06-29',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 01:36:04',
                'updated_at' => '2017-07-27 01:36:04',
            ),
            26 => 
            array (
                'id' => 27,
                'master_code' => 'AA7242',
                'document_id' => 6,
                'doc_number' => 'CT/UNJBG-597549',
                'date_expedition' => '2017-07-06',
                'position_id' => 3,
                'recognized' => 1,
                'labor_id' => 2,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-04',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-27 02:29:15',
                'updated_at' => '2017-07-27 02:29:15',
            ),
            27 => 
            array (
                'id' => 28,
                'master_code' => 'AA7242',
                'document_id' => 5,
                'doc_number' => 'RR/UNJBG-224458',
                'date_expedition' => '2017-07-05',
                'position_id' => 1,
                'recognized' => 1,
                'labor_id' => 4,
                'condition' => 'Condicion',
                'since' => '2017-08-10',
                'until' => '2017-08-17',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-28 03:45:15',
                'updated_at' => '2017-07-28 03:45:15',
            ),
            28 => 
            array (
                'id' => 29,
                'master_code' => 'AA7242',
                'document_id' => 22,
                'doc_number' => 'RF/UNJBG-548754',
                'date_expedition' => '2017-07-03',
                'position_id' => 4,
                'recognized' => 1,
                'labor_id' => 3,
                'condition' => 'Condicion',
                'since' => '2017-07-03',
                'until' => '2017-07-26',
                'institution' => 'Institucion',
                'observation' => NULL,
                'created_at' => '2017-07-28 04:06:07',
                'updated_at' => '2017-07-28 04:06:07',
            ),
        ));
        
        
    }
}
